# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: osx
language: r
r: 3.6.3
r_github_packages: jasp-stats/jaspTools
before_install: 
  - "git clone --branch=MacOS-Original https://github.com/jasp-stats/jasp-required-files.git ~/pkgs"
script:
  - R < tests/testthat.R --no-save
env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
    - VDIFFR_RUN_TESTS=true
    - REQUIRED_PKGS=~/pkgs
